/**
 * src/sdaxList.js
 * Statische Liste mit SDAX-Einzelwerten (Yahoo-Ticker auf Xetra/.DE).
 * Quelle: https://en.wikipedia.org/wiki/SDAX
 */

'use strict';

const SDAX_STOCKS = [
  { provider: 'SDAX', ticker: '1U1.DE', name: '1&1 AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'ADN.DE', name: 'Adesso SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'ADTN.DE', name: 'Adtran Networks SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'ALZ.DE', name: 'Alzchem Group AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'AAD.DE', name: 'Amadeus FiRe AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'AOF.DE', name: 'Atoss Software AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'BFSA.DE', name: 'Befesa S.A.', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'BVB.DE', name: 'Borussia Dortmund GmbH & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'COK.DE', name: 'Cancom SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'CWC.DE', name: 'Cewe Stiftung & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'DMP.DE', name: 'Dermapharm Holding SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'DBAN.DE', name: 'Deutsche Beteiligungs AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'DEQ.DE', name: 'Deutsche Euroshop AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'DEZ.DE', name: 'Deutz AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'DOU.DE', name: 'Douglas Holding AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'DRW.DE', name: 'Drägerwerk AG & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'DUE.DE', name: 'Dürr AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'EUZ.DE', name: 'Eckert & Ziegler Strahlen- und Medizintechnik AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'ELG.DE', name: 'Elmos Semiconductor SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'EKT.DE', name: 'Energiekontor AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'EVT.DE', name: 'Evotec SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'FYB.DE', name: 'Formycon AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'GFT.DE', name: 'GFT Technologies SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'GYC.DE', name: 'Grand City Properties S.A.', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'GLJ.DE', name: 'Grenke AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'HAB.DE', name: 'Hamborner Reit AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'HDD.DE', name: 'Heidelberger Druckmaschinen AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'HBH.DE', name: 'Hornbach Holding AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'HYQ.DE', name: 'Hypoport SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'INH.DE', name: 'Indus Holding AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'JEN.DE', name: 'Jenoptik AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'JST.DE', name: 'Jost Werke AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'KCO.DE', name: 'Klöckner & Co SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'KBC.DE', name: 'Kontron AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'KSB.DE', name: 'KSB SE & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'KWS.DE', name: 'KWS Saat SE & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'LPK.DE', name: 'LPKF Laser & Electronics AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'MBB.DE', name: 'MBB SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'MLP.DE', name: 'MLP SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'MUT.DE', name: 'Mutares SE & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'NA9.DE', name: 'Nagarro SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'NOEJ.DE', name: 'Norma Group SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'PAT.DE', name: 'Patrizia SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'PBB.DE', name: 'PBB AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'PNE3.DE', name: 'PNE AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'PCZ.DE', name: 'ProCredit Holding AG & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'PSM.DE', name: 'ProSiebenSat.1 Media SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'TPE.DE', name: 'PVA TePla AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'SFQ.DE', name: 'SAF-Holland SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'SZG.DE', name: 'Salzgitter AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'SHA.DE', name: 'Schaeffler AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: '1SXP.DE', name: 'Schott Pharma AG & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'YSN.DE', name: 'Secunet Security Networks AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'F3C.DE', name: 'SFC Energy AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'WAF.DE', name: 'Siltronic AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'SIX2.DE', name: 'Sixt SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'S92.DE', name: 'SMA Solar Technology AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'SPN.DE', name: 'Springer Nature AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'STM.DE', name: 'Stabilus S.A.', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'STO3.DE', name: 'Sto SE & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'SAX.DE', name: 'Stratec SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'SZU.DE', name: 'Südzucker AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'SMHN.DE', name: 'Süss MicroTec SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'TNX.DE', name: 'Thyssenkrupp Nucera AG & Co. KGaA', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'V3V.DE', name: 'Verve Group SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'VOS.DE', name: 'Vossloh AG', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'WAC.DE', name: 'Wacker Neuson SE', isin: '', wkn: '' },
  { provider: 'SDAX', ticker: 'WUW.DE', name: 'Wüstenrot & Württembergische AG', isin: '', wkn: '' },
];

module.exports = SDAX_STOCKS;